version: '2'

services:
  app:
    build: ./app/api
    container_name: app
    depends_on:
      - db
    links:
      - db
    ports:
    - "8080:8080"
    environment:
    - DISPLAY=$DISPLAY

   # - QT_QPA_PLATFORM=linuxfb
  #      - QT_LOGGING_RULES='.debug=false;qt.qpa.=false'
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
