version: '3'


services:
  app:
    build: ./app/api
    container_name: app
    depends_on:
      - db
    links:
      - db
    ports:
    - "8080:8080"
    environment:
    - QT_QPA_PLATFORM=linuxfb
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
