# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_xml/add_transp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from backend.backend import *

class Ui_Form(object):
    def __init__(self):
        super().__init__()
        self.qwid = QtWidgets.QWidget()
        self.setupUi(self.qwid)
        self.qwid.show()

    def preset(self):
        self.kind_of_tr.addItems(get_kind_of_transport_list())

    def add_tr_clicked(self):
        name = self.tr_name.text()
        kind_of_transport = self.kind_of_tr.currentText()
        number_of_seats = int(self.seats.value())
        add_new_transport(name, kind_of_transport, number_of_seats)
        self.qwid.close()

    def set_connections(self):
        self.add_tr.clicked.connect(self.add_tr_clicked)

    def setupUi(self, Form):
        self.Form = Form
        Form.setObjectName("Form")
        Form.resize(634, 241)
        self.tr_name = QtWidgets.QLineEdit(Form)
        self.tr_name.setGeometry(QtCore.QRect(200, 50, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.tr_name.setFont(font)
        self.tr_name.setObjectName("tr_name")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.seats = QtWidgets.QSpinBox(Form)
        self.seats.setGeometry(QtCore.QRect(200, 130, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.seats.setFont(font)
        self.seats.setMaximum(99999)
        self.seats.setObjectName("seats")
        self.add_tr = QtWidgets.QPushButton(Form)
        self.add_tr.setGeometry(QtCore.QRect(270, 170, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.add_tr.setFont(font)
        self.add_tr.setObjectName("add_tr")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 130, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 561, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.kind_of_tr = QtWidgets.QComboBox(Form)
        self.kind_of_tr.setGeometry(QtCore.QRect(200, 90, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.kind_of_tr.setFont(font)
        self.kind_of_tr.setObjectName("kind_of_tr")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")

        self.preset()
        self.set_connections()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_8.setText(_translate("Form", "Name:"))
        self.add_tr.setText(_translate("Form", "ADD"))
        self.label_12.setText(_translate("Form", "Number of seats:"))
        self.label_5.setText(_translate("Form", "Transport:"))
        self.label_9.setText(_translate("Form", "Kind of transport:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
