# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_xml/add_ticket.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from backend.backend import *


class Ui_Form(object):
    def __init__(self):
        super().__init__()
        self.qwid = QtWidgets.QWidget()
        self.setupUi(self.qwid)
        self.qwid.show()

    def add_tick_click(self):
        name = self.tick_name.text()
        add_new_ticket(name)
        self.qwid.close()

    def set_connections(self):
        self.add_tick.clicked.connect(self.add_tick_click)


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(522, 155)
        self.add_tick = QtWidgets.QPushButton(Form)
        self.add_tick.setGeometry(QtCore.QRect(220, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.add_tick.setFont(font)
        self.add_tick.setObjectName("add_tick")
        self.tick_name = QtWidgets.QLineEdit(Form)
        self.tick_name.setGeometry(QtCore.QRect(150, 50, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.tick_name.setFont(font)
        self.tick_name.setObjectName("tick_name")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")

        self.set_connections()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_tick.setText(_translate("Form", "ADD"))
        self.label_6.setText(_translate("Form", "Ticket:"))
        self.label_13.setText(_translate("Form", "Name of class"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
