# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_xml/add_kind_of_transp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from backend.backend import *


class Ui_Form(object):

    def __init__(self):
        super().__init__()
        self.qwid = QtWidgets.QWidget()
        self.setupUi(self.qwid)
        self.qwid.show()

    def add_kind_click(self):
        name = self.tick_name_3.text()
        add_kind_of_transport(name)
        self.qwid.close()

    def set_connections(self):
        self.add_kind.clicked.connect(self.add_kind_click)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(601, 153)
        self.add_kind = QtWidgets.QPushButton(Form)
        self.add_kind.setGeometry(QtCore.QRect(250, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.add_kind.setFont(font)
        self.add_kind.setObjectName("add_kind")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(10, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.tick_name_3 = QtWidgets.QLineEdit(Form)
        self.tick_name_3.setGeometry(QtCore.QRect(160, 50, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.tick_name_3.setFont(font)
        self.tick_name_3.setObjectName("tick_name_3")

        self.set_connections()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_kind.setText(_translate("Form", "ADD"))
        self.label_23.setText(_translate("Form", "Name of kind"))
        self.label_24.setText(_translate("Form", "Kind of transport:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
