# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui_xml/flights.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1160, 450)
        Dialog.setMinimumSize(QtCore.QSize(1160, 450))
        Dialog.setMaximumSize(QtCore.QSize(1160, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./frontend/resources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.apply = QtWidgets.QPushButton(Dialog)
        self.apply.setGeometry(QtCore.QRect(1010, 400, 141, 41))
        self.apply.setObjectName("apply")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 1141, 381))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1139, 379))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.toolBox = QtWidgets.QToolBox(self.scrollAreaWidgetContents)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 1101, 171))
        self.toolBox.setObjectName("toolBox")
        self.Stage = QtWidgets.QWidget()
        self.Stage.setGeometry(QtCore.QRect(0, 0, 1101, 111))
        self.Stage.setObjectName("Stage")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Stage)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1101, 111))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.from_text = QtWidgets.QLabel(self.page_3)
        self.from_text.setGeometry(QtCore.QRect(40, 0, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.from_text.setFont(font)
        self.from_text.setScaledContents(True)
        self.from_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.from_text.setObjectName("from_text")
        self.depdate_text = QtWidgets.QLabel(self.page_3)
        self.depdate_text.setGeometry(QtCore.QRect(40, 20, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.depdate_text.setFont(font)
        self.depdate_text.setScaledContents(True)
        self.depdate_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.depdate_text.setObjectName("depdate_text")
        self.to_text = QtWidgets.QLabel(self.page_3)
        self.to_text.setGeometry(QtCore.QRect(40, 70, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.to_text.setFont(font)
        self.to_text.setScaledContents(True)
        self.to_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.to_text.setObjectName("to_text")
        self.arrdate_text = QtWidgets.QLabel(self.page_3)
        self.arrdate_text.setGeometry(QtCore.QRect(40, 90, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.arrdate_text.setFont(font)
        self.arrdate_text.setScaledContents(True)
        self.arrdate_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.arrdate_text.setObjectName("arrdate_text")
        self.from_point = QtWidgets.QLabel(self.page_3)
        self.from_point.setGeometry(QtCore.QRect(230, 0, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.from_point.setFont(font)
        self.from_point.setScaledContents(True)
        self.from_point.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.from_point.setObjectName("from_point")
        self.depdate = QtWidgets.QLabel(self.page_3)
        self.depdate.setGeometry(QtCore.QRect(230, 20, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.depdate.setFont(font)
        self.depdate.setScaledContents(True)
        self.depdate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.depdate.setObjectName("depdate")
        self.to_point = QtWidgets.QLabel(self.page_3)
        self.to_point.setGeometry(QtCore.QRect(230, 70, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.to_point.setFont(font)
        self.to_point.setScaledContents(True)
        self.to_point.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.to_point.setObjectName("to_point")
        self.arrdate = QtWidgets.QLabel(self.page_3)
        self.arrdate.setGeometry(QtCore.QRect(230, 90, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.arrdate.setFont(font)
        self.arrdate.setScaledContents(True)
        self.arrdate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.arrdate.setObjectName("arrdate")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setGeometry(QtCore.QRect(4, 0, 41, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./frontend/resources/from.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(4, 60, 41, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./frontend/resources/to.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.transport = QtWidgets.QLabel(self.page_3)
        self.transport.setGeometry(QtCore.QRect(540, 0, 61, 51))
        self.transport.setText("")
        self.transport.setPixmap(QtGui.QPixmap("./frontend/resources/plane.png"))
        self.transport.setScaledContents(True)
        self.transport.setObjectName("transport")
        self.ticket_type = QtWidgets.QLabel(self.page_3)
        self.ticket_type.setGeometry(QtCore.QRect(610, 0, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.ticket_type.setFont(font)
        self.ticket_type.setScaledContents(True)
        self.ticket_type.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ticket_type.setObjectName("ticket_type")
        self.time = QtWidgets.QLabel(self.page_3)
        self.time.setGeometry(QtCore.QRect(670, 60, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.time.setFont(font)
        self.time.setScaledContents(True)
        self.time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.time.setObjectName("time")
        self.time_text = QtWidgets.QLabel(self.page_3)
        self.time_text.setGeometry(QtCore.QRect(540, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.time_text.setFont(font)
        self.time_text.setScaledContents(True)
        self.time_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_text.setObjectName("time_text")
        self.cost_text = QtWidgets.QLabel(self.page_3)
        self.cost_text.setGeometry(QtCore.QRect(790, 60, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.cost_text.setFont(font)
        self.cost_text.setScaledContents(True)
        self.cost_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cost_text.setObjectName("cost_text")
        self.cost = QtWidgets.QLabel(self.page_3)
        self.cost.setGeometry(QtCore.QRect(960, 60, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.cost.setFont(font)
        self.cost.setScaledContents(True)
        self.cost.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cost.setObjectName("cost")
        self.dist_text = QtWidgets.QLabel(self.page_3)
        self.dist_text.setGeometry(QtCore.QRect(540, 90, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.dist_text.setFont(font)
        self.dist_text.setScaledContents(True)
        self.dist_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dist_text.setObjectName("dist_text")
        self.dist = QtWidgets.QLabel(self.page_3)
        self.dist.setGeometry(QtCore.QRect(670, 90, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.dist.setFont(font)
        self.dist.setScaledContents(True)
        self.dist.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dist.setObjectName("dist")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.toolBox.addItem(self.Stage, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 1101, 111))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TicketBase - Available flights"))
        self.apply.setText(_translate("Dialog", "Apply"))
        self.from_text.setText(_translate("Dialog", "From:"))
        self.depdate_text.setText(_translate("Dialog", "Departure date:"))
        self.to_text.setText(_translate("Dialog", "To:"))
        self.arrdate_text.setText(_translate("Dialog", "Arrival date:"))
        self.from_point.setText(_translate("Dialog", "[from]"))
        self.depdate.setText(_translate("Dialog", "[dep. date]"))
        self.to_point.setText(_translate("Dialog", "[to]"))
        self.arrdate.setText(_translate("Dialog", "[arr. date]"))
        self.ticket_type.setText(_translate("Dialog", "Business class"))
        self.time.setText(_translate("Dialog", "[time delta]"))
        self.time_text.setText(_translate("Dialog", "Flight time:"))
        self.cost_text.setText(_translate("Dialog", "Cost:"))
        self.cost.setText(_translate("Dialog", "[cost]"))
        self.dist_text.setText(_translate("Dialog", "Distance:"))
        self.dist.setText(_translate("Dialog", "[distance]"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Stage), _translate("Dialog", "Stage 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Dialog", "Page 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
