# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui_xml/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 720)
        Dialog.setMinimumSize(QtCore.QSize(1280, 720))
        Dialog.setMaximumSize(QtCore.QSize(1280, 720))
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./frontend/resources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setAutoFillBackground(False)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(29, 130, 1181, 521))
        self.scrollArea.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1158, 519))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1131, 141))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(230, 100, 121, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.plane_check = QtWidgets.QCheckBox(self.groupBox)
        self.plane_check.setGeometry(QtCore.QRect(630, 30, 21, 21))
        self.plane_check.setText("")
        self.plane_check.setObjectName("plane_check")
        self.train_check = QtWidgets.QCheckBox(self.groupBox)
        self.train_check.setGeometry(QtCore.QRect(630, 90, 21, 21))
        self.train_check.setText("")
        self.train_check.setObjectName("train_check")
        self.plane = QtWidgets.QLabel(self.groupBox)
        self.plane.setGeometry(QtCore.QRect(660, 10, 71, 61))
        self.plane.setText("")
        self.plane.setPixmap(QtGui.QPixmap("./frontend/resources/plane.png"))
        self.plane.setScaledContents(True)
        self.plane.setObjectName("plane")
        self.train = QtWidgets.QLabel(self.groupBox)
        self.train.setGeometry(QtCore.QRect(660, 70, 71, 61))
        self.train.setText("")
        self.train.setPixmap(QtGui.QPixmap("./frontend/resources/train.png"))
        self.train.setScaledContents(True)
        self.train.setObjectName("train")
        self.econ = QtWidgets.QCheckBox(self.groupBox)
        self.econ.setGeometry(QtCore.QRect(780, 19, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.econ.setFont(font)
        self.econ.setObjectName("econ")
        self.first = QtWidgets.QCheckBox(self.groupBox)
        self.first.setGeometry(QtCore.QRect(780, 80, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.first.setFont(font)
        self.first.setObjectName("first")
        self.business = QtWidgets.QCheckBox(self.groupBox)
        self.business.setGeometry(QtCore.QRect(780, 50, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.business.setFont(font)
        self.business.setObjectName("business")
        self.from_list = QtWidgets.QComboBox(self.groupBox)
        self.from_list.setGeometry(QtCore.QRect(230, 11, 361, 31))
        self.from_list.setObjectName("from_list")
        self.to_list = QtWidgets.QComboBox(self.groupBox)
        self.to_list.setGeometry(QtCore.QRect(230, 50, 361, 31))
        self.to_list.setObjectName("to_list")
        self.search = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.search.setGeometry(QtCore.QRect(972, 467, 171, 41))
        self.search.setObjectName("search")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 1131, 151))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.add_flight = QtWidgets.QPushButton(self.groupBox_2)
        self.add_flight.setGeometry(QtCore.QRect(492, 0, 150, 150))
        self.add_flight.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./frontend/resources/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_flight.setIcon(icon1)
        self.add_flight.setIconSize(QtCore.QSize(128, 128))
        self.add_flight.setObjectName("add_flight")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.sign = QtWidgets.QLabel(Dialog)
        self.sign.setGeometry(QtCore.QRect(28, 663, 591, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sign.setFont(font)
        self.sign.setStyleSheet("QLabel {\n"
"color: white;\n"
"}")
        self.sign.setTextFormat(QtCore.Qt.RichText)
        self.sign.setScaledContents(True)
        self.sign.setObjectName("sign")
        self.git = QtWidgets.QPushButton(Dialog)
        self.git.setGeometry(QtCore.QRect(1030, 660, 181, 51))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./frontend/resources/git.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.git.setIcon(icon2)
        self.git.setIconSize(QtCore.QSize(64, 64))
        self.git.setObjectName("git")
        self.auth = QtWidgets.QPushButton(Dialog)
        self.auth.setGeometry(QtCore.QRect(1030, 10, 181, 51))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./frontend/resources/auth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.auth.setIcon(icon3)
        self.auth.setIconSize(QtCore.QSize(48, 48))
        self.auth.setObjectName("auth")
        self.weth_icon = QtWidgets.QLabel(Dialog)
        self.weth_icon.setGeometry(QtCore.QRect(1030, 70, 51, 51))
        self.weth_icon.setText("")
        self.weth_icon.setPixmap(QtGui.QPixmap("./frontend/resources/weth.png"))
        self.weth_icon.setScaledContents(True)
        self.weth_icon.setObjectName("weth_icon")
        self.weth = QtWidgets.QLabel(Dialog)
        self.weth.setGeometry(QtCore.QRect(1090, 69, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.weth.setFont(font)
        self.weth.setStyleSheet("QLabel {\n"
"color: white;\n"
"}")
        self.weth.setObjectName("weth")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1281, 721))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("./frontend/resources/background.jpg"))
        self.label_4.setObjectName("label_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_2.setGeometry(QtCore.QRect(30, 130, 1181, 521))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1179, 519))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 1131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 1131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setGeometry(QtCore.QRect(10, 380, 1131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.week = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.week.setGeometry(QtCore.QRect(20, 410, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.week.setFont(font)
        self.week.setObjectName("week")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.week)
        self.month = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.month.setGeometry(QtCore.QRect(20, 430, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.month.setFont(font)
        self.month.setObjectName("month")
        self.buttonGroup.addButton(self.month)
        self.threem = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.threem.setGeometry(QtCore.QRect(20, 450, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.threem.setFont(font)
        self.threem.setObjectName("threem")
        self.buttonGroup.addButton(self.threem)
        self.year = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.year.setGeometry(QtCore.QRect(20, 470, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.year.setFont(font)
        self.year.setObjectName("year")
        self.buttonGroup.addButton(self.year)
        self.alltime = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.alltime.setGeometry(QtCore.QRect(20, 490, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.alltime.setFont(font)
        self.alltime.setObjectName("alltime")
        self.buttonGroup.addButton(self.alltime)
        self.leave = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.leave.setGeometry(QtCore.QRect(430, 410, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.leave.setFont(font)
        self.leave.setObjectName("leave")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.leave)
        self.visit = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.visit.setGeometry(QtCore.QRect(430, 430, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.visit.setFont(font)
        self.visit.setObjectName("visit")
        self.buttonGroup_2.addButton(self.visit)
        self.classes = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.classes.setGeometry(QtCore.QRect(430, 450, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.classes.setFont(font)
        self.classes.setObjectName("classes")
        self.buttonGroup_2.addButton(self.classes)
        self.transp = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.transp.setGeometry(QtCore.QRect(430, 470, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.transp.setFont(font)
        self.transp.setObjectName("transp")
        self.buttonGroup_2.addButton(self.transp)
        self.graph = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.graph.setGeometry(QtCore.QRect(1000, 467, 141, 41))
        self.graph.setObjectName("graph")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.from_line = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.from_line.setGeometry(QtCore.QRect(160, 61, 291, 21))
        self.from_line.setObjectName("from_line")
        self.to_line = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.to_line.setGeometry(QtCore.QRect(160, 90, 291, 21))
        self.to_line.setObjectName("to_line")
        self.plane_2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.plane_2.setGeometry(QtCore.QRect(480, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.plane_2.setFont(font)
        self.plane_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./frontend/resources/plane.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plane_2.setIcon(icon4)
        self.plane_2.setIconSize(QtCore.QSize(64, 64))
        self.plane_2.setObjectName("plane_2")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.plane_2)
        self.train_2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.train_2.setGeometry(QtCore.QRect(480, 80, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.train_2.setFont(font)
        self.train_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./frontend/resources/train.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.train_2.setIcon(icon5)
        self.train_2.setIconSize(QtCore.QSize(64, 64))
        self.train_2.setObjectName("train_2")
        self.buttonGroup_3.addButton(self.train_2)
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox.setGeometry(QtCore.QRect(600, 40, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_2.setGeometry(QtCore.QRect(600, 70, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_3.setGeometry(QtCore.QRect(600, 100, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_15.setGeometry(QtCore.QRect(780, 60, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_16.setGeometry(QtCore.QRect(780, 90, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.depdate = QtWidgets.QDateEdit(self.scrollAreaWidgetContents_2)
        self.depdate.setGeometry(QtCore.QRect(1020, 60, 121, 22))
        self.depdate.setObjectName("depdate")
        self.arrdate = QtWidgets.QDateEdit(self.scrollAreaWidgetContents_2)
        self.arrdate.setGeometry(QtCore.QRect(1020, 90, 121, 22))
        self.arrdate.setObjectName("arrdate")
        self.to_line_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.to_line_3.setGeometry(QtCore.QRect(160, 140, 131, 21))
        self.to_line_3.setObjectName("to_line_3")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_17.setGeometry(QtCore.QRect(10, 140, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_18.setGeometry(QtCore.QRect(320, 140, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.to_line_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.to_line_4.setGeometry(QtCore.QRect(500, 140, 91, 21))
        self.to_line_4.setObjectName("to_line_4")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setGeometry(QtCore.QRect(600, 140, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.to_line_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.to_line_5.setGeometry(QtCore.QRect(780, 140, 91, 21))
        self.to_line_5.setObjectName("to_line_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 240, 1131, 121))
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.from_text = QtWidgets.QLabel(self.page_3)
        self.from_text.setGeometry(QtCore.QRect(40, 0, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.from_text.setFont(font)
        self.from_text.setScaledContents(True)
        self.from_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.from_text.setObjectName("from_text")
        self.depdate_text = QtWidgets.QLabel(self.page_3)
        self.depdate_text.setGeometry(QtCore.QRect(40, 20, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.depdate_text.setFont(font)
        self.depdate_text.setScaledContents(True)
        self.depdate_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.depdate_text.setObjectName("depdate_text")
        self.to_text = QtWidgets.QLabel(self.page_3)
        self.to_text.setGeometry(QtCore.QRect(40, 70, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.to_text.setFont(font)
        self.to_text.setScaledContents(True)
        self.to_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.to_text.setObjectName("to_text")
        self.arrdate_text = QtWidgets.QLabel(self.page_3)
        self.arrdate_text.setGeometry(QtCore.QRect(40, 90, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.arrdate_text.setFont(font)
        self.arrdate_text.setScaledContents(True)
        self.arrdate_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.arrdate_text.setObjectName("arrdate_text")
        self.from_point = QtWidgets.QLabel(self.page_3)
        self.from_point.setGeometry(QtCore.QRect(230, 0, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.from_point.setFont(font)
        self.from_point.setScaledContents(True)
        self.from_point.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.from_point.setObjectName("from_point")
        self.depdate_2 = QtWidgets.QLabel(self.page_3)
        self.depdate_2.setGeometry(QtCore.QRect(230, 20, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.depdate_2.setFont(font)
        self.depdate_2.setScaledContents(True)
        self.depdate_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.depdate_2.setObjectName("depdate_2")
        self.to_point = QtWidgets.QLabel(self.page_3)
        self.to_point.setGeometry(QtCore.QRect(230, 70, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.to_point.setFont(font)
        self.to_point.setScaledContents(True)
        self.to_point.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.to_point.setObjectName("to_point")
        self.arrdate_2 = QtWidgets.QLabel(self.page_3)
        self.arrdate_2.setGeometry(QtCore.QRect(230, 90, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.arrdate_2.setFont(font)
        self.arrdate_2.setScaledContents(True)
        self.arrdate_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.arrdate_2.setObjectName("arrdate_2")
        self.label_20 = QtWidgets.QLabel(self.page_3)
        self.label_20.setGeometry(QtCore.QRect(4, 0, 41, 51))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("./frontend/resources/from.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_3)
        self.label_21.setGeometry(QtCore.QRect(4, 60, 41, 51))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("./frontend/resources/to.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.transport = QtWidgets.QLabel(self.page_3)
        self.transport.setGeometry(QtCore.QRect(540, 0, 61, 51))
        self.transport.setText("")
        self.transport.setPixmap(QtGui.QPixmap("./frontend/resources/plane.png"))
        self.transport.setScaledContents(True)
        self.transport.setObjectName("transport")
        self.ticket_type = QtWidgets.QLabel(self.page_3)
        self.ticket_type.setGeometry(QtCore.QRect(610, 0, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.ticket_type.setFont(font)
        self.ticket_type.setScaledContents(True)
        self.ticket_type.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ticket_type.setObjectName("ticket_type")
        self.time = QtWidgets.QLabel(self.page_3)
        self.time.setGeometry(QtCore.QRect(670, 60, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.time.setFont(font)
        self.time.setScaledContents(True)
        self.time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.time.setObjectName("time")
        self.time_text = QtWidgets.QLabel(self.page_3)
        self.time_text.setGeometry(QtCore.QRect(540, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.time_text.setFont(font)
        self.time_text.setScaledContents(True)
        self.time_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_text.setObjectName("time_text")
        self.cost_text = QtWidgets.QLabel(self.page_3)
        self.cost_text.setGeometry(QtCore.QRect(870, 60, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.cost_text.setFont(font)
        self.cost_text.setScaledContents(True)
        self.cost_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cost_text.setObjectName("cost_text")
        self.cost = QtWidgets.QLabel(self.page_3)
        self.cost.setGeometry(QtCore.QRect(960, 60, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.cost.setFont(font)
        self.cost.setScaledContents(True)
        self.cost.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cost.setObjectName("cost")
        self.dist_text = QtWidgets.QLabel(self.page_3)
        self.dist_text.setGeometry(QtCore.QRect(540, 90, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.dist_text.setFont(font)
        self.dist_text.setScaledContents(True)
        self.dist_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dist_text.setObjectName("dist_text")
        self.dist = QtWidgets.QLabel(self.page_3)
        self.dist.setGeometry(QtCore.QRect(670, 90, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.dist.setFont(font)
        self.dist.setScaledContents(True)
        self.dist.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dist.setObjectName("dist")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.delete_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.delete_2.setGeometry(QtCore.QRect(1000, 190, 141, 41))
        self.delete_2.setObjectName("delete_2")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setGeometry(QtCore.QRect(10, 360, 1131, 31))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setGeometry(QtCore.QRect(10, 160, 1131, 31))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.add_fl = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.add_fl.setGeometry(QtCore.QRect(1000, 130, 141, 41))
        self.add_fl.setObjectName("add_fl")
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.week.raise_()
        self.month.raise_()
        self.threem.raise_()
        self.year.raise_()
        self.alltime.raise_()
        self.leave.raise_()
        self.visit.raise_()
        self.classes.raise_()
        self.transp.raise_()
        self.graph.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.from_line.raise_()
        self.to_line.raise_()
        self.plane_2.raise_()
        self.train_2.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.depdate.raise_()
        self.arrdate.raise_()
        self.to_line_3.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.to_line_4.raise_()
        self.label_19.raise_()
        self.to_line_5.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.delete_2.raise_()
        self.stackedWidget.raise_()
        self.add_fl.raise_()
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_4.raise_()
        self.scrollArea.raise_()
        self.sign.raise_()
        self.git.raise_()
        self.auth.raise_()
        self.weth_icon.raise_()
        self.weth.raise_()
        self.scrollArea_2.raise_()

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TicketBase - Main Window (User)"))
        self.label.setText(_translate("Dialog", "From:"))
        self.label_2.setText(_translate("Dialog", "To:"))
        self.label_3.setText(_translate("Dialog", "Departure date:"))
        self.econ.setText(_translate("Dialog", "Economy class"))
        self.first.setText(_translate("Dialog", "First class"))
        self.business.setText(_translate("Dialog", "Business class"))
        self.search.setText(_translate("Dialog", "Search"))
        self.sign.setText(_translate("Dialog", "Saint-Petersburg, 2020"))
        self.git.setText(_translate("Dialog", "Project link"))
        self.auth.setText(_translate("Dialog", "Authorization"))
        self.weth.setText(_translate("Dialog", "+12 °C"))
        self.label_5.setText(_translate("Dialog", "New flight:"))
        self.label_6.setText(_translate("Dialog", "Data base:"))
        self.label_7.setText(_translate("Dialog", "Statistics:"))
        self.week.setText(_translate("Dialog", "Week"))
        self.month.setText(_translate("Dialog", "Month"))
        self.threem.setText(_translate("Dialog", "3 months"))
        self.year.setText(_translate("Dialog", "Year"))
        self.alltime.setText(_translate("Dialog", "All time"))
        self.leave.setText(_translate("Dialog", "Top cities to leave"))
        self.visit.setText(_translate("Dialog", "Top cities to visit"))
        self.classes.setText(_translate("Dialog", "Classes statistics"))
        self.transp.setText(_translate("Dialog", "Popularity of transport types"))
        self.graph.setText(_translate("Dialog", "Get graph"))
        self.label_8.setText(_translate("Dialog", "From:"))
        self.label_9.setText(_translate("Dialog", "To:"))
        self.checkBox.setText(_translate("Dialog", "Economy class"))
        self.checkBox_2.setText(_translate("Dialog", "Business class"))
        self.checkBox_3.setText(_translate("Dialog", "First class"))
        self.label_15.setText(_translate("Dialog", "Departure date:"))
        self.label_16.setText(_translate("Dialog", "Arrival date:"))
        self.label_17.setText(_translate("Dialog", "Distance, km:"))
        self.label_18.setText(_translate("Dialog", "Flight time, min.:"))
        self.label_19.setText(_translate("Dialog", "Cost, Rub.:"))
        self.from_text.setText(_translate("Dialog", "From:"))
        self.depdate_text.setText(_translate("Dialog", "Departure date:"))
        self.to_text.setText(_translate("Dialog", "To:"))
        self.arrdate_text.setText(_translate("Dialog", "Arrival date:"))
        self.from_point.setText(_translate("Dialog", "[from]"))
        self.depdate_2.setText(_translate("Dialog", "[dep. date]"))
        self.to_point.setText(_translate("Dialog", "[to]"))
        self.arrdate_2.setText(_translate("Dialog", "[arr. date]"))
        self.ticket_type.setText(_translate("Dialog", "Business class"))
        self.time.setText(_translate("Dialog", "[time delta]"))
        self.time_text.setText(_translate("Dialog", "Flight time:"))
        self.cost_text.setText(_translate("Dialog", "Cost:"))
        self.cost.setText(_translate("Dialog", "[cost]"))
        self.dist_text.setText(_translate("Dialog", "Distance:"))
        self.dist.setText(_translate("Dialog", "[distance]"))
        self.delete_2.setText(_translate("Dialog", "Delete flight"))
        self.add_fl.setText(_translate("Dialog", "Add flight"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
