# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui_xml/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 720)
        Dialog.setMinimumSize(QtCore.QSize(1280, 720))
        Dialog.setMaximumSize(QtCore.QSize(1280, 720))
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:/study/NoSQL/ticketsDB/icon_airplane.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setAutoFillBackground(False)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(29, 130, 1181, 521))
        self.scrollArea.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1158, 519))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1131, 141))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(230, 100, 121, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.plane_check = QtWidgets.QCheckBox(self.groupBox)
        self.plane_check.setGeometry(QtCore.QRect(630, 30, 21, 21))
        self.plane_check.setText("")
        self.plane_check.setObjectName("plane_check")
        self.train_check = QtWidgets.QCheckBox(self.groupBox)
        self.train_check.setGeometry(QtCore.QRect(630, 90, 21, 21))
        self.train_check.setText("")
        self.train_check.setObjectName("train_check")
        self.plane = QtWidgets.QLabel(self.groupBox)
        self.plane.setGeometry(QtCore.QRect(660, 10, 71, 61))
        self.plane.setText("")
        self.plane.setPixmap(QtGui.QPixmap("./gui_xml\\../resources/plane.png"))
        self.plane.setScaledContents(True)
        self.plane.setObjectName("plane")
        self.train = QtWidgets.QLabel(self.groupBox)
        self.train.setGeometry(QtCore.QRect(660, 70, 71, 61))
        self.train.setText("")
        self.train.setPixmap(QtGui.QPixmap("./gui_xml\\../resources/train.png"))
        self.train.setScaledContents(True)
        self.train.setObjectName("train")
        self.econ = QtWidgets.QCheckBox(self.groupBox)
        self.econ.setGeometry(QtCore.QRect(780, 19, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.econ.setFont(font)
        self.econ.setObjectName("econ")
        self.first = QtWidgets.QCheckBox(self.groupBox)
        self.first.setGeometry(QtCore.QRect(780, 80, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.first.setFont(font)
        self.first.setObjectName("first")
        self.business = QtWidgets.QCheckBox(self.groupBox)
        self.business.setGeometry(QtCore.QRect(780, 50, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.business.setFont(font)
        self.business.setObjectName("business")
        self.from_list = QtWidgets.QComboBox(self.groupBox)
        self.from_list.setGeometry(QtCore.QRect(230, 11, 361, 31))
        self.from_list.setObjectName("from_list")
        self.to_list = QtWidgets.QComboBox(self.groupBox)
        self.to_list.setGeometry(QtCore.QRect(230, 50, 361, 31))
        self.to_list.setObjectName("to_list")
        self.search = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.search.setGeometry(QtCore.QRect(972, 467, 171, 41))
        self.search.setObjectName("search")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 1131, 151))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.add_flight = QtWidgets.QPushButton(self.groupBox_2)
        self.add_flight.setGeometry(QtCore.QRect(492, 0, 150, 150))
        self.add_flight.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./gui_xml\\../resources/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_flight.setIcon(icon1)
        self.add_flight.setIconSize(QtCore.QSize(128, 128))
        self.add_flight.setObjectName("add_flight")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.sign = QtWidgets.QLabel(Dialog)
        self.sign.setGeometry(QtCore.QRect(28, 663, 591, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sign.setFont(font)
        self.sign.setStyleSheet("QLabel {\n"
"color: white;\n"
"}")
        self.sign.setTextFormat(QtCore.Qt.RichText)
        self.sign.setScaledContents(True)
        self.sign.setObjectName("sign")
        self.git = QtWidgets.QPushButton(Dialog)
        self.git.setGeometry(QtCore.QRect(1030, 660, 181, 51))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("E:/study/NoSQL/ticketsDB/Ei-sc-github.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.git.setIcon(icon2)
        self.git.setIconSize(QtCore.QSize(64, 64))
        self.git.setObjectName("git")
        self.auth = QtWidgets.QPushButton(Dialog)
        self.auth.setGeometry(QtCore.QRect(1030, 10, 181, 51))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("E:/study/NoSQL/ticketsDB/noavatar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.auth.setIcon(icon3)
        self.auth.setIconSize(QtCore.QSize(48, 48))
        self.auth.setObjectName("auth")
        self.weth_icon = QtWidgets.QLabel(Dialog)
        self.weth_icon.setGeometry(QtCore.QRect(1030, 70, 51, 51))
        self.weth_icon.setText("")
        self.weth_icon.setPixmap(QtGui.QPixmap("E:/study/NoSQL/ticketsDB/clouds-37009_960_720-e1504784569994.png"))
        self.weth_icon.setScaledContents(True)
        self.weth_icon.setObjectName("weth_icon")
        self.weth = QtWidgets.QLabel(Dialog)
        self.weth.setGeometry(QtCore.QRect(1090, 69, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.weth.setFont(font)
        self.weth.setStyleSheet("QLabel {\n"
"color: white;\n"
"}")
        self.weth.setObjectName("weth")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1281, 721))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("E:/study/NoSQL/ticketsDB/maxresdefault.jpg"))
        self.label_4.setObjectName("label_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_2.setGeometry(QtCore.QRect(30, 130, 1181, 521))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1179, 519))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_4.raise_()
        self.scrollArea.raise_()
        self.sign.raise_()
        self.git.raise_()
        self.auth.raise_()
        self.weth_icon.raise_()
        self.weth.raise_()
        self.scrollArea_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TicketBase - Main Window (User)"))
        self.label.setText(_translate("Dialog", "From:"))
        self.label_2.setText(_translate("Dialog", "To:"))
        self.label_3.setText(_translate("Dialog", "Departure date:"))
        self.econ.setText(_translate("Dialog", "Economy class"))
        self.first.setText(_translate("Dialog", "First class"))
        self.business.setText(_translate("Dialog", "Business class"))
        self.search.setText(_translate("Dialog", "Search"))
        self.sign.setText(_translate("Dialog", "Saint-Petersburg, 2020"))
        self.git.setText(_translate("Dialog", "Project link"))
        self.auth.setText(_translate("Dialog", "Authorization"))
        self.weth.setText(_translate("Dialog", "+12 °C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
