# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_xml/statis.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os, pymongo, numpy
from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
import datetime
from dateutil.relativedelta import relativedelta
from backend.backend import *

class Ui_Form(object):
    def __init__(self):
        super().__init__()
        self.qwid = QtWidgets.QWidget()
        self.setupUi(self.qwid)
        self.qwid.show()

    def set_connections(self):
        self.graph.clicked.connect(self.graph_button_click)

    def graph_button_click(self):
        now = datetime.datetime.now()
        start_date = None
        if self.week.isChecked():
            start_date = now - datetime.timedelta(days=datetime.date.today().weekday(), weeks=1)
        if self.month.isChecked():
            start_date = now - relativedelta(months=1)
        if self.threem.isChecked():
            start_date = now - relativedelta(months=3)
        if self.year.isChecked():
            start_date = now - relativedelta(years=1)
        if self.alltime.isChecked(): now = None

        trips = stat(start_date, now)

        if self.leave.isChecked():
            cities = get_cities()
            heights = numpy.zeros(len(cities))
            for i in range(len(trips)):
                heights[cities.index(trips[i]['from'])] += 1
            x = numpy.arange(len(cities))
            plt.bar(x, height=heights)
            plt.xticks(x, cities)
            plt.title('Top cities to leave')

        if self.visit.isChecked():
            cities = get_cities()
            heights = numpy.zeros(len(cities))
            for i in range(len(trips)):
                heights[cities.index(trips[i]['to'])] += 1
            x = numpy.arange(len(cities))
            plt.bar(x, height=heights)
            plt.xticks(x, cities)
            plt.title('Top cities to visit')

        if self.classes.isChecked():
            classes = get_tickets()
            heights = numpy.zeros(len(classes))
            for i in range(len(trips)):
                heights[classes.index(get_ticket_type_name(trips[i]['ticket_id']))] += 1
            x = numpy.arange(len(classes))
            plt.bar(x, height=heights)
            plt.xticks(x, classes)
            plt.title('Classes statistics')

        if self.transp.isChecked():
            types = get_transport()
            heights = numpy.zeros(len(types))
            for i in range(len(trips)):
                heights[types.index(get_transport_type_name(trips[i]['transport_id']))] += 1
            x = numpy.arange(len(types))
            plt.bar(x, height=heights)
            plt.xticks(x, types)
            plt.title('Popularity of flights')

        plt.grid()
        plt.show()


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(462, 258)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 0, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.graph = QtWidgets.QPushButton(Form)
        self.graph.setGeometry(QtCore.QRect(110, 200, 141, 41))
        self.graph.setObjectName("graph")
        self.threem = QtWidgets.QRadioButton(Form)
        self.threem.setGeometry(QtCore.QRect(10, 70, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.threem.setFont(font)
        self.threem.setObjectName("threem")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.threem)
        self.month = QtWidgets.QRadioButton(Form)
        self.month.setGeometry(QtCore.QRect(10, 50, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.month.setFont(font)
        self.month.setObjectName("month")
        self.buttonGroup.addButton(self.month)
        self.year = QtWidgets.QRadioButton(Form)
        self.year.setGeometry(QtCore.QRect(10, 90, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.year.setFont(font)
        self.year.setObjectName("year")
        self.buttonGroup.addButton(self.year)
        self.alltime = QtWidgets.QRadioButton(Form)
        self.alltime.setGeometry(QtCore.QRect(10, 110, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.alltime.setFont(font)
        self.alltime.setObjectName("alltime")
        self.buttonGroup.addButton(self.alltime)
        self.week = QtWidgets.QRadioButton(Form)
        self.week.setGeometry(QtCore.QRect(10, 30, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.week.setFont(font)
        self.week.setChecked(True)
        self.week.setObjectName("week")
        self.buttonGroup.addButton(self.week)
        self.leave = QtWidgets.QRadioButton(Form)
        self.leave.setGeometry(QtCore.QRect(250, 20, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.leave.setFont(font)
        self.leave.setChecked(True)
        self.leave.setObjectName("leave")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.leave)
        self.transp = QtWidgets.QRadioButton(Form)
        self.transp.setGeometry(QtCore.QRect(250, 110, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.transp.setFont(font)
        self.transp.setObjectName("transp")
        self.buttonGroup_2.addButton(self.transp)
        self.classes = QtWidgets.QRadioButton(Form)
        self.classes.setGeometry(QtCore.QRect(250, 80, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.classes.setFont(font)
        self.classes.setObjectName("classes")
        self.buttonGroup_2.addButton(self.classes)
        self.visit = QtWidgets.QRadioButton(Form)
        self.visit.setGeometry(QtCore.QRect(250, 50, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.visit.setFont(font)
        self.visit.setObjectName("visit")
        self.buttonGroup_2.addButton(self.visit)

        self.set_connections()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Statistics:"))
        self.graph.setText(_translate("Form", "Get graph"))
        self.threem.setText(_translate("Form", "3 months"))
        self.month.setText(_translate("Form", "Month"))
        self.year.setText(_translate("Form", "Year"))
        self.alltime.setText(_translate("Form", "All time"))
        self.week.setText(_translate("Form", "Week"))
        self.leave.setText(_translate("Form", "Top cities to leave"))
        self.transp.setText(_translate("Form", "Popularity of flights"))
        self.classes.setText(_translate("Form", "Classes statistics"))
        self.visit.setText(_translate("Form", "Top cities to visit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
