# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_xml/trip_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QWidget):
    def __init__(self, scrollArea):
        super().__init__()
        self.scrollArea = scrollArea
        self.setupUi()

    def setupUi(self):
        #layout = QtWidgets.QGridLayout()

        #self.setLayout(layout)
        #self.label = QtWidgets.QLabel()
        #self.label.setGeometry(QtCore.QRect(0, 0, 55, 16))
        #self.label.setObjectName("label")
        #self.pushButton = QtWidgets.QPushButton()
        #layout.addWidget(self.label)
        #layout.addWidget(self.pushButton)

        #self.pushButton.setGeometry(QtCore.QRect(70, 100, 20, 30))
        #self.pushButton.setObjectName("pushButton")

        #_translate = QtCore.QCoreApplication.translate
        #self.label.setText(_translate("Form", "Kek"))
        #self.pushButton.setText(_translate("Form", "PushButton"))

        self.scrollArea = QtWidgets.QScrollArea(self.scrollArea)
        #self.scrollArea.setGeometry(QtCore.QRect(50, 130, 120, 87))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 118, 85))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(20, 50, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(40, 20, 55, 16))
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        _translate = QtCore.QCoreApplication.translate
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.label.setText(_translate("Form", "Kek"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
